apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: policy
  namespace: exploit
spec:
  kprobes:
  - call: "sys_execve"
    syscall: true
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/usr/bin/find"
      matchActions:
      - action: Post
        stackTrace: true
      - action: Sigkill